version: "3"

services:
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=pontarias
      - POSTGRES_DB=pontarias
      - POSTGRES_PASSWORD=123
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "2345:5432"
  backend:
    build: .
    environment:
      - DB_DATABASE=pontarias
      - DB_USERNAME=pontarias
      - DB_PASSWORD=123
      - DB_DIALECT=postgresql
      - DB_PORT=
    ports:
      - "10281:3000"
    depends_on:
      - database

