version: "3"

services:
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=pontarias
      - POSTGRES_DB=pontarias
      - POSTGRES_PASSWORD=123
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  backend:
    build: .
    environment:
      - DATABASE=pontarias
      - USERNAME=pontarias
      - PASSWORD=123
      - DIALECT=postgresql
    ports:
      - "10281:3000"
    depends_on:
      - database

