version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    networks:
      - pontarias
    environment:
      - POSTGRES_USER=pontarias
      - POSTGRES_DB=pontarias
      - POSTGRES_PASSWORD=123
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "2345:5432"
  pontarias_back:
    build: .
    container_name: pontarias_back
    networks:
      - pontarias
    environment:
      - DB_DATABASE=pontarias
      - DB_USERNAME=pontarias
      - DB_PASSWORD=123
      - DB_DIALECT=postgres
      - DB_HOST=postgres
    ports:
      - "10281:3000"
    depends_on:
      - postgres

networks:
  pontarias:
    name: pontarias
