name: EsLint

on:
  push:
    - master
  pull_request:
    - *
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: ESLint
      - uses: stefanoeb/eslint-action@1.0.2