name: EsLint

on:
  push:
    branch:
      - "master"
  pull_request:
    branch:
      - "*"
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: ESLint
      - uses: stefanoeb/eslint-action@1.0.2