name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          ./node_modules/.bin/eslint --ignore-path .eslintignore .
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true